# Generated by Django 5.0.4 on 2024-07-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
