# Generated by Django 5.0.4 on 2024-07-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizgroup'),
        ),
        migrations.AddField(
            model_name='completedlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by_users', to='course.lesson', verbose_name='lesson'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.section', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='video',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='course.lesson', verbose_name='lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='completedlesson',
            unique_together={('user', 'lesson')},
        ),
    ]
