# Generated by Django 5.0.4 on 2024-07-23 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_lessons_per_part_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_enrollments', to='course.coursepart', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'part enrollment',
                'verbose_name_plural': 'part enrollments',
                'db_table': 'part_enrollment',
                'ordering': ['created_at'],
                'unique_together': {('part', 'user')},
            },
        ),
    ]
