# Generated by Django 5.0.4 on 2024-07-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursebookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('user', 'course', 'created_at'), 'verbose_name': 'enrollment', 'verbose_name_plural': 'enrollments'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order',), 'verbose_name': 'lesson', 'verbose_name_plural': 'lessons'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',), 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='partenrollment',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_enrollments', to='course.coursepart'),
        ),
    ]
