# Generated by Django 5.0.4 on 2024-08-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_category_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_open',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
