# Generated by Django 5.0.4 on 2024-07-22 11:28

import config.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/')),
                ('video', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quiz',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Choice',
                'verbose_name_plural': 'Quiz Choices',
                'db_table': 'quiz_choice',
                'ordering': ['quiz', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizGroup',
            fields=[
                ('id', config.utils.CustomIDField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Quiz Group',
                'verbose_name_plural': 'Quiz Groups',
                'db_table': 'quiz_group',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.quizgroup'),
        ),
        migrations.CreateModel(
            name='QuizSolution',
            fields=[
                ('id', config.utils.CustomIDField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('sample_question', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='answer/')),
                ('video', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Quiz Solution',
                'verbose_name_plural': 'Quiz Solutions',
                'db_table': 'quiz_solution',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.quizsolution'),
        ),
    ]
