# Generated by Django 5.0.4 on 2024-07-23 11:12

import config.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgroup',
            name='id',
            field=config.utils.CustomIDField(editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
