# Generated by Django 5.0.4 on 2024-07-31 09:06

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'faq category',
                'verbose_name_plural': 'faq categories',
                'db_table': 'faq_category',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='config',
            name='id',
            field=config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.faqcategory')),
            ],
            options={
                'verbose_name': 'faq',
                'verbose_name_plural': 'faqs',
                'db_table': 'faq',
                'ordering': ('question',),
            },
        ),
    ]
