# Generated by Django 5.0.4 on 2024-07-31 09:35

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_faq_question_alter_faqcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contact',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('id',), 'verbose_name': 'faq', 'verbose_name_plural': 'faqs'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ('id',), 'verbose_name': 'faq category', 'verbose_name_plural': 'faq categories'},
        ),
    ]
