# Generated by Django 5.0.4 on 2024-08-01 05:57

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_type',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('voice', 'Voice')], default='text', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', config.utils.CustomIDField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('media', models.FileField(upload_to='message-media/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='chat.message')),
            ],
            options={
                'verbose_name': 'message media',
                'verbose_name_plural': 'message medias',
                'db_table': 'message_media',
                'ordering': ('id',),
            },
        ),
    ]
