# Generated by Django 5.0.4 on 2024-08-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_media_remove_message_media_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemedia',
            old_name='media',
            new_name='file',
        ),
    ]
